name: 'app-linux'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-tauri:
    permissions:
      contents: write

    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Write mah build config
        run: |
          echo "{\"name\": \"Mah\", \"mobile\":true}" > custom-build-config.json

      - name: install mah dependencies
        run: npm install

      - name: Install tauri dependencies
        run: cd resources/apps && npm install

      - name: Build linux app
        run: |
          cd resources/apps
          npm run linux

      - name: upload linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'linux'
          path: resources/apps/tauri/target/release/bundle/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: resources/apps/tauri/target/release/bundle/**/*
