name: 'app-macos'

on:
  workflow_dispatch:

jobs:
  build-tauri:
    permissions:
      contents: write

    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Write mah build config
        run: |
          echo "{\"name\": \"Mah\", \"mobile\":true}" > custom-build-config.json

      - name: install mah dependencies
        run: npm install

      - name: Install tauri dependencies
        run: cd resources/apps && npm install

      - uses: tauri-apps/tauri-action@v0
        id: build_os
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: resources/apps
          args: '--target aarch64-apple-darwin'

      - name: upload macos artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'macos'
          path: "${{ join(fromJSON(steps.build_os.outputs.artifactPaths), '\n') }}"
